# Default values for croc-hunter.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

serviceType: ClusterIP
servicePort: 80
containerPort: 8080
component: "croc-hunter"
replicas: 3
#image: acrjdtest.azurecr.io/acrjdtest/crochunter
image: docker.io/oveits/crochunter
imageTag: master
imagePullPolicy: Always
## If you have a private registry you specify a secret to use --- add note about how secrets work with jenkinsfile set// 
imagePullSecrets: 
  name: croc-hunter-secrets
cpu: "10m"
memory: "128Mi"
## Ingress settings
ingress:
  enabled: true
  hostname: crochunter.codefresh.vocon-it.com
  annotations:
     kubernetes.io/ingress.class: nginx
     certmanager.k8s.io/cluster-issuer: letsencrypt-prod
     kubernetes.io/tls-acme: "true"
  tls: true
## PodDisruptionBudget
pdb:
  enabled: false
  minAvailable: 2
## Config Map
commit:
  sha: "8c149d9"
  branch: "master"
  repo : "oveits/crochunter"
test:
  seleniumHubUrl: "http://selenium-hub-url:4444/wd/hub"
  ingressHostname: "{{.Values.ingress.hostname}}"
  imageTag: latest
